### ISSUE TITLE
Super Fast Object Cloner / Allocator with No Constructor and Initialize Overhead by Cloning from a Given Template Object Which was Previously Allocated

### ISSUE THREAD

**Issue by sirinath** [OpenHFT/Java-Lang#43]
Running the constructor logic and initializers take cycles. Is it possible to have a safe fast clone which only retains side effects. (Mainly static field updated I think.)

**Comment by peter-lawrey** [comment]
Roman, can you review this?

**Comment by leventov** [comment]
I don't think this is relevant anymore.
