### ISSUE TITLE
Error in AbstractBytes.writeUTFΔ(long offset, int maxSize, @Nullable CharSequence s)  when remaining() == 0

### ISSUE THREAD

**Issue by belousa** [OpenHFT/Java-Lang#47]
(lang-6.4.4.jar)

When I call writeUTFΔ with offset, I get the following exception:

 java.lang.IllegalArgumentException: encoded string too long: 24 bytes, remaining=0
	at net.openhft.lang.io.AbstractBytes.findUTFLength(AbstractBytes.java:838)
	at net.openhft.lang.io.AbstractBytes.writeUTFΔ(AbstractBytes.java:803)

The exception happens when position() of the buffer is set to its size so remaining() returns 0.

I believe remaining() should not be relevant when offset is passed to the writeUTFΔ, only the sum of offset and string length is important.

**Comment by peter-lawrey** [comment]
This should be fixed now.
