### ISSUE TITLE
New write() Methods in Bytes

### ISSUE THREAD

**Issue by pjulien** [OpenHFT/Java-Lang#54]
Please consider adding positional buffer write methods to ``NativeBytes``.  Currently the only available method that comes close is:

```
    void write(long offset, byte[] bytes, int off, int len);
```

However I am writing lock free many to one and one to many ring buffers.  Not having a positional index makes it very difficult because I can't use/move the position of any of the buffers.

If the following write methods

```
  void write(long offset, ByteBuffer bytes, int off, int len);
  void write(long offset, Bytes bytes, int off, int len);
```

were added it would make this use case possible.

I have the same problem for reading, I am using buffers but only ``byte[]`` is supported via:

```
void readFully(long offset, @NotNull byte[] bytes, int off, int len);
```

**Comment by peter-lawrey** [comment]
Can you not set the position and limit of the ByteBuffer and Bytes when you
read/write?

**Comment by pjulien** [comment]
> Can you not set the position and limit of the ByteBuffer and Bytes when you
> read/write?

The buffer backing the ring buffer is visible to multiple writers and a reader.  So no, I cannot.

I could change the position and limit of the source buffer when writing into the ring buffer but I would still be unable to read back from this buffer when it comes time to read from it.

**Comment by leventov** [comment]
BTW you can use MultiStoreBytes to solve the problem right now. But I agree such methods would be useful.

**Comment by peter-lawrey** [comment]
I agree the methods would be useful. Btw you can take a ByteBuffer.slice ()
or Bytes.bytes () of a buffer and access the same memory using different
positions and limits.

**Comment by pjulien** [comment]
Thank you for your suggestions but I am trying to stay allocation free in this part of the system.  I am there other than for this call.

**Comment by peter-lawrey** [comment]
These functions have been added to Chronicle Bytes
