### ISSUE TITLE
Java-Lang  don't include the license file

### ISSUE THREAD

**Issue by puntogil** [OpenHFT/Java-Lang#75]
Hi
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
Thanks in advance
Regards

**Comment by peter-lawrey** [comment]
This module is under community support only. If you wish to issue a pull
request we would be happy to consider it.

**Comment by peter-lawrey** [comment]
This LICENSE file was updated in Jun last year

https://github.com/OpenHFT/Java-Lang/blob/master/LICENSE

But it existed long before that.

**Comment by puntogil** [comment]
hi
thanks!
most of the files in this project uses the Apache License, Version 2.0
but the license file, which has been added, is LGPLv3. the project is to be considered with dual license?
again thanks
regards

**Comment by peter-lawrey** [comment]
Can I ask what you are using Java-Lang for?

All the products which use it have been moved to "community support" as
these are no longer the latest version of any project.

**Comment by puntogil** [comment]
hi
i used this library for import https://github.com/reactor/reactor used in the Spring Framework projects
regards

**Comment by peter-lawrey** [comment]
Hi,

Would you be interested in migrating to
https://github.com/OpenHFT/Chronicle-Queue/ v4, which uses Chronicle Bytes?

Regards,
   Peter.

**Comment by puntogil** [comment]
sorry, at the moment i have too much work for upgrade some packages used in Fedora (Wildfly 10)
but in the near future i can try to switch in the v4 branch
regards
