### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [OpenHFT/Java-Lang#76]
Hi

The following source files are without license headers:

./lang/src/main/java/net/openhft/lang/io/VanillaBytesHash.java

./lang/src/test/java/net/openhft/lang/io/BytesTest.java
./lang/src/test/java/net/openhft/lang/values/BuySell.java
./lang/src/test/java/net/openhft/lang/values/BuySellValues.java
./lang/src/test/java/net/openhft/lang/values/EnumValuesTest.java
./lang/src/test/java/net/openhft/lang/values/StringValueTest.java

Please, confirm the licensing of code and/or content/s, and add license headers.

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by peter-lawrey** [comment]
I have made sure that Apache 2.0 is the only license for the project, and
it appears on all classes.
