### ISSUE TITLE
README hard to read due to error in markdown syntax

### ISSUE THREAD

**Issue by Markvy** [OpenHFT/Java-Lang#79]
The readme ( https://github.com/OpenHFT/Java-Lang/blob/master/README.md )currently has this:

####Example
    ByteBuffer byteBuffer = ByteBuffer.allocate(SIZE);
    ByteBufferBytes bytes = new ByteBufferBytes(byteBuffer);
    for (long i = 0; i < bytes.maximumLimit(); i++)
        bytes.writeLong(i);
    for (long i = bytes.maximumLimit()-8; i >= 0; i -= 8) {
        int j = bytes.readLong(i);
        assert i ==  j;
    }

I think the intention is to have this:

#### Example
    ByteBuffer byteBuffer = ByteBuffer.allocate(SIZE);
    ByteBufferBytes bytes = new ByteBufferBytes(byteBuffer);
    for (long i = 0; i < bytes.maximumLimit(); i++)
        bytes.writeLong(i);
    for (long i = bytes.maximumLimit()-8; i >= 0; i -= 8) {
        int j = bytes.readLong(i);
        assert i ==  j;
    }

The extra space before the word "Example" makes a big difference here.  (Well, actually, here at least the line breaks come out okay; in the actual readme even those disappear for some reason.)

**Comment by peter-lawrey** [comment]
Can you issue a pull request?

Btw Chronicle Bytes replaces this now.

**Comment by Markvy** [comment]
I know almost nothing about git or github, so let's see how badly I mess this up.

Btw, if this is replaced by Chronicle Bytes, shouldn't the Readme mention that as well?

**Comment by peter-lawrey** [comment]
I agree. It should.
