### ISSUE TITLE
A question about the commit 43da9545f

### ISSUE THREAD

**Issue by tao-ji** [OpenHFT/Java-Lang#84]
Hi,

I am doing some research on the evolution of your projects Java-Lang and Chronicle-Queue. I find that the committed date and the authored date are exactly same between this commit 43da9545f(https://github.com/OpenHFT/Java-Lang/commit/43da9545f37a575a744abed89cd4536f3a7f2dcb) and the commit 8d7dea7ef(https://github.com/OpenHFT/Chronicle-Queue/commit/8d7dea7efc9403a9720b6e058cd91b5b0afb6571) of Chronicle-Queue. As far as I know, if we use the pick-up of Git, we can reserve the same authored date but with the different committed date. Would you please tell me how you applied this commit into another repository?
Thank you!

Best,
Tao Ji

**Comment by dpisklov** [comment]
Intellij's git plugin can commit across several projects. 
This is irrelevant to the project so I'm closing the issue. In the future please use stackoverflow for questions, github is for real issues.
