### ISSUE TITLE
Versions beyond 6.8.2 not published to maven repo

### ISSUE THREAD

**Issue by saint-cygnum** [OpenHFT/Java-Lang#86]
As the title suggests.

**Comment by saint-cygnum** [comment]
Then perhaps your public chronicle bom needs an up to NOT to refer artifacts published internally?

**Comment by dpisklov** [comment]
Our bom refers to our enterprise projects as well as opensource projects, for the benefit of our customers. None of the enterprise projects are available to public (unless one buys a license). It is up to the user to understand which projects are available.

**Comment by saint-cygnum** [comment]
Ok.

**Comment by saint-cygnum** [comment]
Ok. Thanks.
